### ISSUE TITLE
Rename project to emerald-explorer

### ISSUE THREAD

**Issue by BelfordZ** [ETCDEVTeam/emerald-explorer#8]
This app is most similar to what others would call an explorer.

**Comment by shanejonas** [comment]
yea tough to find the right thing to call it. but i've seen block explorers with write access like deploying contracts or sending sign txes like etherscan for example:

![image](https://user-images.githubusercontent.com/364566/44806559-26cc0780-ab7c-11e8-9957-66c1a6f41657.png)


so at least theres precedents for it in things called explorers lol

**Comment by shanejonas** [comment]
project has been renamed!
